<?php

namespace ForumCube\SteamIntegeration\Extend\Entity;

use XF\Mvc\Entity\Entity;
use XF\Mvc\Entity\Structure;

class UserOption extends XFCP_UserOption
{
    public static function getStructure(Structure $structure)
    {
        $response = parent::getStructure($structure);
        $structure->columns['fc_steam_data'] = ['type' => Entity::UINT, 'default' => 0];
        return $response;
    }

    protected function _preSave()
    {
        $response = parent::_preSave(); // TODO: Change the autogenerated stub

        $request = \XF::App()->request();
        $input = $request->filter([
                'fc_steam_data' => 'uint'
                ]
        );

        $this->bulkSet($input);

        return $response;

    }
}
